### ISSUE TITLE
Crash during project loading

### ISSUE THREAD

**Issue by Macoron** [Macoron/gpt4all.unity#1]
I've been reported that project may crash during opening in Unity. Still researching why it could be the case, but if you are experiencing something similar, try to checkout this commit:

https://github.com/Macoron/gpt4all.unity/commit/67aeaabfb72aef34b3261395eaf02fcb97b81edd

Please report in this issue if you have this problem and if checkout to other commit helped you.

**Comment by Jhayphal** [comment]
I have this problem and checkout to other commit helped me :)

**Comment by Lexazan** [comment]
Same here, https://github.com/Macoron/gpt4all.unity/commit/67aeaabfb72aef34b3261395eaf02fcb97b81edd did the trick

**Comment by Macoron** [comment]
#6 should fix that, reopen if it doesn't
