### ISSUE TITLE
AI respond to the instructions with every prompt

### ISSUE THREAD

**Issue by millennIumAMbiguity** [Macoron/gpt4all.unity#13]
When filling out a larger instruction, the AI starts to pay less attention to the prompt and responds primarily with the instruction in mind.

I tried to fix this by removing the formation of the print input and instead giving it an initial print in init. This worked with smaller instructions but when given a longer instruction it refused to respond.

**Comment by Macoron** [comment]
Could you send some example with prompt and LLM output?

**Comment by Macoron** [comment]
AI answers are random, due to temperature settings. Each time you can get different answer for same prompt.

**Comment by millennIumAMbiguity** [comment]
yes, but it did always answer with a greeting and reaction followed by some sentence ending in checkmate. This happened every time I ran it. but now the issue does not occur.

**Comment by Macoron** [comment]
Alright, I'll close this issue for now. Feel free to reopen if problem occurs again and you have chat logs.
