### ISSUE TITLE
problema with dll

### ISSUE THREAD

**Issue by pokelocos** [Macoron/gpt4all.unity#2]
I Clone the repository to be able to use it, downloaded the models "ggml-mpt-7b-chat" and "ggml-gpt4all-j-v1.3-groovy", I'm using the default one and it seems to take it well, but then it gives me the following error:

`DllNotFoundException: libllmodel assembly:<unknown assembly> type:<unknown type> member:(null)
Gpt4All.LlmWrapper.InitFromPath (Gpt4All.LlmModelType type, System.String modelPath) (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:161)
Gpt4All.LlmWrapper+<>c__DisplayClass25_0.<InitFromPathAsync>b__0 () (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:198)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <5d4cbfbeb62e454f98e19b231866113e>:0)
System.Threading.Tasks.Task.Execute () (at <5d4cbfbeb62e454f98e19b231866113e>:0)
--- End of stack trace from previous location where exception was thrown ---
Gpt4All.LlmWrapper.InitFromPathAsync (Gpt4All.LlmModelType type, System.String modelPath) (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:199)
Gpt4All.LlmManager.InitModel () (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:111)
UnityEngine.Debug:LogException(Exception)
Gpt4All.<InitModel>d__34:MoveNext() (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:119)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Gpt4All.<InitFromPathAsync>d__25:MoveNext() (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:199)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

This message appears in the console when I hit play in the editor. I'm not sure if I'm missing a step or doing something wrong. I'm using Unity version 2022.2.9f1. I appreciate any information you can provide.
`

**Comment by Macoron** [comment]
It looks like Unity can't load .dll for some reason. Could you try to checkout earlier commit, like it suggested in #1?

**Comment by pokelocos** [comment]
It's working, thank you very much! For a moment, I thought it wasn't, but I was mistaken. I was loading "LLAMA" instead of "GPTJ," even though I'm using "Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin." Everything is working fine now, hopefully, the issue with the recent commits gets fixed. :)

**Comment by pokelocos** [comment]
I celebrated too soon. Everything is working fine with English sentences, but I am Hispanic, and I would like to develop things in Spanish. However, Unity crashes and closes when I ask it to respond in Spanish. I assume that "Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin" is a model that is not prepared to respond in Spanish. Do you know which model supports communication in Spanish? I suppose it has issues with letters with accents and strange characters.

I would also appreciate knowing what all the parameters that the controller class allows to modify do. :)

**Comment by Lexazan** [comment]
I have some random crashes from time to time using English (not much, but like 10 crashed in ~500 sessions), but I tried with other languages and it seems like using non English prompts greatly increase the crash chance. Basically all (around 10) my tries resulted in a unity crash on first to third prompt.

**Comment by guoyong0318** [comment]
I got this error：
Plugins: Failed to load 'D:/gpt4all.unity-master/Library/PackageCache/com.gpt4all.unity@548076b369/Plugins/Windows/libllama.dll' because one or more of its dependencies could not be loaded.

**Comment by Macoron** [comment]
@Lexazan could you check latest master? With #6 it should be more stable.

**Comment by Zercerium** [comment]
```
DllNotFoundException: llmodel assembly:<unknown assembly> type:<unknown type> member:(null)
Gpt4All.LlmWrapper.InitFromPath (Gpt4All.LlmModelType type, System.String modelPath) (at Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:175)
```

sadly got the same error on a M1 Pro Mac. Cloned the current repo (also tried older version) placed different models in the folder and every time got the same error.

**Comment by Macoron** [comment]
@Zercerium thanks for reporting this! Could you check if latest master fixed that? I included missing dependency that broke dylib.

**Comment by Zercerium** [comment]
yeah, the latest commit fixed the issue. Thanks a lot!

**Comment by Macoron** [comment]
> yeah, the latest commit fixed the issue. Thanks a lot!

Great, I hopes this finally stabilized problems with compiled libs
