### ISSUE TITLE
C# bindings

### ISSUE THREAD

**Issue by vitaliy00000** [Macoron/gpt4all.unity#3]
Is it possible to use these DLLs (libllama.dll, libllmodel.dll) that in your project for a Windows console application using Target Framework .NET 6 or .NET 7 to run gpt4all?

**Comment by Macoron** [comment]
Some parts of this bindings can be reused, but mostly code is adapted for Unity exclusive features, like `MonoBehaviour` or Unity life cycle. You would probably be more interested in the official pure C# bindings that should be merged in original repo soon.

https://github.com/nomic-ai/gpt4all/pull/650

**Comment by mvenditto** [comment]
Alpha version of the bindings has been merged. Any feedback would be greatly appreciated!
