### ISSUE TITLE
Error: libllama.dll and libllmodel.dll

### ISSUE THREAD

**Issue by BaMarcy** [Macoron/gpt4all.unity#4]
I encountered an issue when attempting to add a repository as a Unity Package to my existing project using the Git URL in Unity Package Manager. The error logs indicate that two DLL files, namely **libllama.dll** and **libllmodel.dll**, along with their dependencies, could not be loaded.

Steps to Reproduce:
    1. Open Unity project.
    2. Go to Unity Package Manager.
    3. Click on the "+" button and select "Add package from git URL".
    4. Enter the Git URL for the repository and proceed.
    5. Wait for the package to be imported.
    6. Observe the error message related to the DLL files and their dependencies not being loaded.
 
**Error Logs:**

- ../Library/PackageCache/com.gpt4all.unity@548076b369/Plugins/Windows/libllama.dll' because one or more of its dependencies could not be loaded.

- ../Library/PackageCache/com.gpt4all.unity@548076b369/Plugins/Windows/libllmodel.dll' because one or more of its dependencies could not be loaded.

Unity3D 2022.2.2f1
Win11

Thanks.

**Comment by Macoron** [comment]
@BaMarcy could you also provide editor logs? Do you have installed visual C++ runtime?

**Comment by guoyong0318** [comment]
I got the same issue，even I had add the Windows Build Support (IL2CPP) module

Plugins: Failed to load 'D:/gpt4all.unity-master/Packages/com.gpt4all.unity/Plugins/Windows/libllama.dll' because one or more of its dependencies could not be loaded.

**Comment by Macoron** [comment]
#6 should fix that, reopen if it doesn't
