### ISSUE TITLE
String conversion error: Partial byte sequence encountered in the input and questions

### ISSUE THREAD

**Issue by Yumiga** [Macoron/gpt4all.unity#7]
Hi ! Sorry to bother you but i am a very beginner in unity ! ^^ I need your help about that error and GPU use in unity :

- I cloned the repository in my project.
- So i end up with 2 folders in my Asset folder named : "Samples" and "StreamingAssets"
- Until there. All was good.
- I have installed Gpt4all on my computer with the "installer for windows" downloaded on their website.
- I cloned llama.ccp repository and used w64devkit to build it.
- I downloaded ggml-gpt4all-j-v1.3-groovy.bin and placed it in StreamingAssets\Gpt4All
- I launched the unity project to see what happen and all worked. 
- But when the chat moves towards the "enter text" in unity, the LLM stops writing its answer in mid-sentence. 
- And I get this error :

ExecutionEngineException: String conversion error: Partial byte sequence encountered in the input.
(wrapper native-to-managed) Gpt4All.LlmWrapper.ResponseCallbackStatic(int,intptr)
Gpt4All.LlmWrapper.Prompt (System.String promptText, Gpt4All.LlmPromptContext context) (at Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:85)
Gpt4All.LlmWrapper+<>c__DisplayClass17_0.<PromptAsync>b__0 () (at Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:99)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <a40b0ad4a868437393ad434631fb6ff1>:0)
System.Threading.Tasks.Task.Execute () (at <a40b0ad4a868437393ad434631fb6ff1>:0)
--- End of stack trace from previous location where exception was thrown ---
Gpt4All.LlmWrapper.PromptAsync (System.String promptText, Gpt4All.LlmPromptContext context) (at Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:100)
Gpt4All.LlmManager.Prompt (System.String rawPrompt) (at Packages/com.gpt4all.unity/Scripts/LlmManager.cs:133)
Gpt4All.Samples.ChatSample.SendToChat (System.String prompt) (at Assets/Samples/1 - Chat/ChatSample.cs:43)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <a40b0ad4a868437393ad434631fb6ff1>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)

Do you have an idea of what it is ?
Did I download and install things correctly ?
And finally, do you know how to use GPU instead of CPU ?

Thanks in advance Macoron !

**Comment by Macoron** [comment]
>Do you have an idea of what it is ?

Looks like you have found a bug in a string conversation. Could you provide prompt that you typed into input field?

I suspect problem is that LLM returned non-English text. I fixed similar bug in https://github.com/Macoron/whisper.unity/pull/34, but I want to double check it with your prompt.

> do you know how to use GPU instead of CPU ?

Sadly, this bindings doesn't support GPU yet.

**Comment by Macoron** [comment]
I think, I fixed that with #8. Reopen if you still has this issue on some prompt.

**Comment by Yumiga** [comment]
> 

Sorry for late answer dude ^^ I didn't think you were this reactive ! I was speaking French when I got that error ^^ ! So yep, i'll check #8 ! That's a shame that it doesn't support GPU yet XD. I hope it will be the case in the future !
