### ISSUE TITLE
Whisper not loaded and failed to load LLM

### ISSUE THREAD

**Issue by Yumiga** [Macoron/gpt4all.unity#9]
Hi Macoron !!!!!!!!! 

It seems i found new errors in unity 😢 and this time, I took screenshots 😁 ! I tried to launch the project in a new unity project this morning and poof 😮! Here come the errors ☹️ ! Take a look at that : 

![issues](https://github.com/Macoron/gpt4all.unity/assets/136904530/490d3ff6-04be-4685-a06c-a09fab6ea35a)

**Comment by Macoron** [comment]
From this logs, it's hard to say what caused this error. Did you downloaded `gpt4all-j-v1.3-groovy.bin` model and put it StreamingAssets folder? Could you redownload it to make sure it's not corrupted?

Could you send [log file](https://docs.unity3d.com/Manual/LogFiles.html) last messages? Maybe there is some clues.

The whisper error is just my lazy copy-paste from another project.

**Comment by arcsidian** [comment]
Same error here on Unity 2022.3.2f1

I just started a fresh project, imported the package, put a working groovy model (tested) in StreamingAssets/Gpt4All and ran the project, I got the same errors, The first 2 errors show instantly, the 3rd error regarding whisper model shows up if I type something and submit it.

Error1:

`Failed to load LLM model!
UnityEngine.Debug:LogError (object)
Gpt4All.LlmWrapper:InitFromPath (Gpt4All.LlmModelType,string) (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:202)
Gpt4All.LlmWrapper/<>c__DisplayClass28_0:<InitFromPathAsync>b__0 () (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:212)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()`

Error2:

`Whisper model isn't loaded! Init Whisper model first!
UnityEngine.Debug:LogError (object)
Gpt4All.LlmManager/<CheckIfLoaded>d__39:MoveNext () (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:142)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:Start<Gpt4All.LlmManager/<CheckIfLoaded>d__39> (Gpt4All.LlmManager/<CheckIfLoaded>d__39&)
Gpt4All.LlmManager:CheckIfLoaded ()
Gpt4All.LlmManager/<Prompt>d__38:MoveNext () (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:129)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:Start<Gpt4All.LlmManager/<Prompt>d__38> (Gpt4All.LlmManager/<Prompt>d__38&)
Gpt4All.LlmManager:Prompt (string)
Gpt4All.Samples.ChatSample/<SendToChat>d__9:MoveNext () (at Assets/Samples/1 - Chat/ChatSample.cs:47)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<Gpt4All.Samples.ChatSample/<SendToChat>d__9> (Gpt4All.Samples.ChatSample/<SendToChat>d__9&)
Gpt4All.Samples.ChatSample:SendToChat (string)
Gpt4All.Samples.ChatSample:OnSubmitPressed () (at Assets/Samples/1 - Chat/ChatSample.cs:35)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
`

3rd error after pressing submit:
`Whisper model isn't loaded! Init Whisper model first!
UnityEngine.Debug:LogError (object)
Gpt4All.LlmManager/<CheckIfLoaded>d__39:MoveNext () (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:142)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:Start<Gpt4All.LlmManager/<CheckIfLoaded>d__39> (Gpt4All.LlmManager/<CheckIfLoaded>d__39&)
Gpt4All.LlmManager:CheckIfLoaded ()
Gpt4All.LlmManager/<Prompt>d__38:MoveNext () (at ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs:129)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:Start<Gpt4All.LlmManager/<Prompt>d__38> (Gpt4All.LlmManager/<Prompt>d__38&)
Gpt4All.LlmManager:Prompt (string)
Gpt4All.Samples.ChatSample/<SendToChat>d__9:MoveNext () (at Assets/Samples/1 - Chat/ChatSample.cs:47)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<Gpt4All.Samples.ChatSample/<SendToChat>d__9> (Gpt4All.Samples.ChatSample/<SendToChat>d__9&)
Gpt4All.Samples.ChatSample:SendToChat (string)
Gpt4All.Samples.ChatSample:OnSubmitPressed () (at Assets/Samples/1 - Chat/ChatSample.cs:35)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
`

**Comment by Macoron** [comment]
@arcsidian Does your editor [log file](https://docs.unity3d.com/Manual/LogFiles.html) contains any additional info? Can't reproduce it on my side with fresh install.

It should look like this or something similar:
```
Trying to load LLM model from C:/Users/dev/TestProject/Assets/StreamingAssets\Gpt4All/test.bin...
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
Gpt4All.LlmWrapper:InitFromPath (Gpt4All.LlmModelType,string) (at ./Library/PackageCache/com.gpt4all.unity@905af96848/Scripts/LlmWrapper.cs:194)
Gpt4All.LlmWrapper/<>c__DisplayClass28_0:<InitFromPathAsync>b__0 () (at ./Library/PackageCache/com.gpt4all.unity@905af96848/Scripts/LlmWrapper.cs:212)
System.Threading.Tasks.Task`1<Gpt4All.LlmWrapper>:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

(Filename: ./Library/PackageCache/com.gpt4all.unity@905af96848/Scripts/LlmWrapper.cs Line: 194)

gptj_model_load: loading model from 'C:/Users/dev/TestProject/Assets/StreamingAssets\Gpt4All/test.bin' - please wait ...
gptj_model_load: invalid model file 'C:/Users/dev/TestProject/Assets/StreamingAssets\Gpt4All/test.bin' (bad magic)
GPT-J ERROR: failed to load model from C:/Users/dev/TestProject/Assets/StreamingAssets\Gpt4All/test.binFailed to load LLM model!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Gpt4All.LlmWrapper:InitFromPath (Gpt4All.LlmModelType,string) (at ./Library/PackageCache/com.gpt4all.unity@905af96848/Scripts/LlmWrapper.cs:202)
Gpt4All.LlmWrapper/<>c__DisplayClass28_0:<InitFromPathAsync>b__0 () (at ./Library/PackageCache/com.gpt4all.unity@905af96848/Scripts/LlmWrapper.cs:212)
System.Threading.Tasks.Task`1<Gpt4All.LlmWrapper>:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

**Comment by arcsidian** [comment]
Trying to load LLM model from C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin...
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
Gpt4All.LlmWrapper:InitFromPath (Gpt4All.LlmModelType,string) (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:194)
Gpt4All.LlmWrapper/<>c__DisplayClass28_0:<InitFromPathAsync>b__0 () (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:212)
System.Threading.Tasks.Task`1<Gpt4All.LlmWrapper>:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

(Filename: ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs Line: 194)

gptj_model_load: loading model from 'C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: invalid model file 'C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin' (bad magic)
GPT-J ERROR: failed to load model from C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.binFailed to load LLM model!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Gpt4All.LlmWrapper:InitFromPath (Gpt4All.LlmModelType,string) (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:202)
Gpt4All.LlmWrapper/<>c__DisplayClass28_0:<InitFromPathAsync>b__0 () (at ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs:212)
System.Threading.Tasks.Task`1<Gpt4All.LlmWrapper>:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

(Filename: ./Packages/com.gpt4all.unity/Scripts/LlmWrapper.cs Line: 202)

Loaded scene 'Temp/__Backupscenes/0.backup'
	Deserialize:            2.468 ms
	Integration:            171.610 ms
	Integration of assets:  0.002 ms
	Thread Wait Time:       0.031 ms
	Total Operation Time:   174.111 ms
NullReferenceException: Object reference not set to an instance of an object
  at Gpt4All.LlmManager.InitModel () [0x000d2] in .\Packages\com.gpt4all.unity\Scripts\LlmManager.cs:114 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Gpt4All.<InitModel>d__37:MoveNext() (at .\Packages\com.gpt4all.unity\Scripts\LlmManager.cs:121)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run(Task, Boolean)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:FinishStageThree()
System.Threading.Tasks.Task`1:TrySetResult(LlmWrapper)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(LlmWrapper)
Gpt4All.<InitFromPathAsync>d__28:MoveNext() (at .\Packages\com.gpt4all.unity\Scripts\LlmWrapper.cs:214)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

(Filename: ./Packages/com.gpt4all.unity/Scripts/LlmManager.cs Line: 114)

[Licensing::Client] Successfully resolved entitlement details
Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
Loaded scene 'Temp/__Backupscenes/0.backup'
	Deserialize:            1.337 ms
	Integration:            130.791 ms
	Integration of assets:  0.001 ms
	Thread Wait Time:       0.007 ms
	Total Operation Time:   132.136 ms
Unloading 65 unused Assets / (480.3 KB). Loaded Objects now: 5650.
Memory consumption went from 164.3 MB to 163.8 MB.
Total: 9.907000 ms (FindLiveObjects: 0.316100 ms CreateObjectMapping: 0.183000 ms MarkObjects: 9.176800 ms  DeleteObjects: 0.230200 ms)

[Licensing::Client] Successfully resolved entitlements
SpriteAtlasPacking completed in 0.002076 sec
Reloading assemblies for play mode.
Reloading assemblies after forced synchronous recompile.
Begin MonoManager ReloadAssembly
Symbol file LoadedFromMemory doesn't match image C:\Development\ProjectGPT\Library\PackageCache\com.unity.visualscripting@1.8.0\Editor\VisualScripting.Core\Dependencies\YamlDotNet\Unity.VisualScripting.YamlDotNet.dll
Symbol file LoadedFromMemory doesn't match image C:\Development\ProjectGPT\Library\PackageCache\com.unity.visualscripting@1.8.0\Editor\VisualScripting.Core\Dependencies\DotNetZip\Unity.VisualScripting.IonicZip.dll
- Loaded All Assemblies, in  0.473 seconds
Refreshing native plugins compatible for Editor in 2.86 ms, found 6 plugins.
Native extension for WindowsStandalone target not found
Native extension for iOS target not found
Native extension for Android target not found
[MODES] ModeService[none].Initialize
[MODES] ModeService[none].LoadModes
[MODES] Loading mode Default (0) for mode-current-id-ProjectGPT
SendMessage cannot be called during Awake, CheckConsistency, or OnValidate (Content: OnRectTransformDimensionsChange)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.RectTransform:set_sizeDelta (UnityEngine.Vector2)
UnityEngine.UI.ScrollRect:SetLayoutHorizontal () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:1171)
UnityEngine.UI.LayoutRebuilder/<>c:<Rebuild>b__12_1 (UnityEngine.Component) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.LayoutRebuilder:PerformLayoutControl (UnityEngine.RectTransform,UnityEngine.Events.UnityAction`1<UnityEngine.Component>) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:124)
UnityEngine.UI.LayoutRebuilder:Rebuild (UnityEngine.UI.CanvasUpdate) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:181)
UnityEngine.Canvas:SendWillRenderCanvases ()
UnityEngine.Canvas:ForceUpdateCanvases ()
UnityEngine.UI.InputField:UpdateLabel () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2541)
UnityEngine.UI.InputField:OnValidate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1115)

[./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs line 1171]

SendMessage cannot be called during Awake, CheckConsistency, or OnValidate (Viewport: OnRectTransformDimensionsChange)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.RectTransform:set_sizeDelta (UnityEngine.Vector2)
UnityEngine.UI.ScrollRect:SetLayoutHorizontal () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:1171)
UnityEngine.UI.LayoutRebuilder/<>c:<Rebuild>b__12_1 (UnityEngine.Component) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.LayoutRebuilder:PerformLayoutControl (UnityEngine.RectTransform,UnityEngine.Events.UnityAction`1<UnityEngine.Component>) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:124)
UnityEngine.UI.LayoutRebuilder:Rebuild (UnityEngine.UI.CanvasUpdate) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:181)
UnityEngine.Canvas:SendWillRenderCanvases ()
UnityEngine.Canvas:ForceUpdateCanvases ()
UnityEngine.UI.InputField:UpdateLabel () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2541)
UnityEngine.UI.InputField:OnValidate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1115)

[./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs line 1171]

SendMessage cannot be called during Awake, CheckConsistency, or OnValidate (Content: OnRectTransformDimensionsChange)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.RectTransform:set_sizeDelta (UnityEngine.Vector2)
UnityEngine.UI.ScrollRect:SetLayoutHorizontal () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:1183)
UnityEngine.UI.LayoutRebuilder/<>c:<Rebuild>b__12_1 (UnityEngine.Component) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.LayoutRebuilder:PerformLayoutControl (UnityEngine.RectTransform,UnityEngine.Events.UnityAction`1<UnityEngine.Component>) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:124)
UnityEngine.UI.LayoutRebuilder:Rebuild (UnityEngine.UI.CanvasUpdate) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:181)
UnityEngine.Canvas:SendWillRenderCanvases ()
UnityEngine.Canvas:ForceUpdateCanvases ()
UnityEngine.UI.InputField:UpdateLabel () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2541)
UnityEngine.UI.InputField:OnValidate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1115)

[./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs line 1183]

SendMessage cannot be called during Awake, CheckConsistency, or OnValidate (Viewport: OnRectTransformDimensionsChange)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.RectTransform:set_sizeDelta (UnityEngine.Vector2)
UnityEngine.UI.ScrollRect:SetLayoutHorizontal () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:1183)
UnityEngine.UI.LayoutRebuilder/<>c:<Rebuild>b__12_1 (UnityEngine.Component) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.LayoutRebuilder:PerformLayoutControl (UnityEngine.RectTransform,UnityEngine.Events.UnityAction`1<UnityEngine.Component>) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:124)
UnityEngine.UI.LayoutRebuilder:Rebuild (UnityEngine.UI.CanvasUpdate) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs:86)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:181)
UnityEngine.Canvas:SendWillRenderCanvases ()
UnityEngine.Canvas:ForceUpdateCanvases ()
UnityEngine.UI.InputField:UpdateLabel () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2541)
UnityEngine.UI.InputField:OnValidate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1115)

[./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs line 1183]

**Comment by Macoron** [comment]
In original message @arcsidian had this error:
```
gptj_model_load: loading model from 'C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: invalid model file 'C:/Development/ProjectGPT/Assets/StreamingAssets\Gpt4All/ggml-gpt4all-j-v1.3-groovy.bin' (bad magic)
```

Bad magic means that beginning of the file damaged or unknown. Hard to tell what might caused that, probably just download error.

@Yumiga check if redownloading fix that for you.

**Comment by Yumiga** [comment]
> 

Okaaaaay ! I'll do it right know and tell ya !!!!!!!!!👌😁😁😁😁😊🤩

**Comment by Yumiga** [comment]
I redownloaded snoozy model and I got the same issues. Now, i'll check the groovy one.

**Comment by Macoron** [comment]
> I redownloaded snoozy model and I got the same issues. Now, i'll check the groovy one.
> 
> Edit : Okay, it worked with groovy ! So I think it depend on the model we use...Thanks for help !🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤯🤯🤯🤯🤯🤯🤯🤪🤪🤪🤪🤪🤪🤪

FYI, groovy has Llama architecture. You should select LLAMA in dropdown `Model Type` in Llm Manager. Also don't use quantized versions, they are not supported yet.

**Comment by Yumiga** [comment]
> > I redownloaded snoozy model and I got the same issues. Now, i'll check the groovy one.
> > Edit : Okay, it worked with groovy ! So I think it depend on the model we use...Thanks for help !🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤯🤯🤯🤯🤯🤯🤯🤪🤪🤪🤪🤪🤪🤪
> 
> FYI, groovy has Llama architecture. You should select LLAMA in dropdown `Model Type` in Llm Manager. Also don't use quantized versions, they are not supported yet.

Woops ! 😅 You 're right ! All issues are now solved !!!!! hehe !!!!!!! Thanks for ALL Macoron !!!!!!!!!!!!!!
